#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-JAPH
version:      0.03
version_from: lib/Acme/JAPH.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
